### ISSUE TITLE
`ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-a??64` is not working

### ISSUE THREAD

**Issue by Harsh4902** [Harsh4902/modbat-JPF#2]
```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-11-openjdk-a??64

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```
Getting this error while running gradle commands

**Comment by Harsh4902** [comment]
@cyrille-artho @pparizek I have used another command to get the `JAVA_HOME` can you please check it?

**Comment by cyrille-artho** [comment]
I see you have already figured this out: Within Gradle, wildcards are not interpreted; within the shell, they are.
Unfortunately, the computer I use with Docker has run out of disk space, so I cannot test the new variant right now.

**Comment by Harsh4902** [comment]
@cyrille-artho No problem, I have checked it. Also, I want to inform that I have tested this on amd based machine. jpf-nhandler's tests are failing on that machine, so I am figuring out that.
